# Generated by Django 5.0.4 on 2024-05-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128)),
                ('phoneNumber', models.CharField(max_length=50)),
            ],
        ),
    ]
