# Generated by Django 5.0.4 on 2024-07-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg', '0004_remove_user_reg_firstname_remove_user_reg_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='first_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_reg',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_reg',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
