# Generated by Django 5.0.4 on 2024-05-31 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_initial'),
        ('user_feedback', '0001_initial'),
        ('user_reg', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=40)),
                ('feedRate', models.CharField(max_length=40)),
                ('feedDesc', models.CharField(max_length=40)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='services.userservices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='user_reg.user_reg')),
            ],
        ),
    ]
