# Generated by Django 5.0.4 on 2024-05-31 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assign_services', '0001_initial'),
        ('services', '0002_initial'),
        ('user_reg', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignServ', models.CharField(max_length=40)),
                ('assignDuty', models.CharField(max_length=40)),
                ('assignStatus', models.CharField(max_length=40)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignservices', to='services.userservices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignservices', to='user_reg.user_reg')),
            ],
        ),
    ]
